apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
    app: octeon-driver-container
  name: octeon-driver-container
  namespace: octeon-test-namespace
spec: {}
---
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    app: octeon-driver
  name: octeon-driver
  namespace: octeon-test-namespace
spec:
  nodeSelector:
    node-role.kubernetes.io/worker: ""
  runPolicy: "Serial"
  triggers:
    - type: "ConfigChange"
    - type: "ImageChange"
  source:
    git:
      ref: "master"
      uri: "https://github.com/openshift-psap/kvc-simple-kmod.git"
    type: Git
    dockerfile: >
      FROM quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:d1dffb4cbbc3cb870c533ed4ba0cdbff8a0081a9226acaa705f1df14a83fdb27


      WORKDIR /build/

      ARG KMODVER

      # Grab the software from upstream

      WORKDIR /build/

      RUN wget http://10.5.210.12/pcie_ep_ref.tar


      RUN wget http://10.5.210.12/bc


      RUN wget http://10.5.210.12/libreadline.so.8


      RUN cp libreadline.so.8 /usr/lib64/


      RUN cp bc /usr/bin


      RUN chmod 777 /usr/bin/bc


      RUN mkdir drivers && tar -xf pcie_ep_ref.tar -C ./drivers/


      RUN cd drivers/pcie_ep_ref/pcie_ep_octeontx-sdk11-devel/host/ && make && make COMPILEFOR=OCTEON_VF


strategy:
  dockerStrategy:
  output:
    to:
      kind: ImageStreamTag
      name: octeon-driver-container:demo