apiVersion: v1
kind: Pod
metadata:
  name: demopod2
  namespace: sriov-network-operator
  annotations:
    k8s.v1.cni.cncf.io/networks: sriov-network-operator/example-sriovnetwork
spec:
  containers:
  - name: ubuntu 
    image: ubuntu
    namespace: sroiv-network-operator
    imagePullPolicy: IfNotPresent
    command: [ "/bin/bash", "-c", "--" ]
    args: [ "while true; do sleep 300000; done;" ]
